"""``conduit-connector-sdk build``: package a connector into one executable file.

Per ``docs/design/20260707-python-connector-sdk.md`` §1.1.6: Conduit execs a
standalone connector subprocess with a **clean environment**
(``cmd.Env = make([]string, 0)`` before appending its own vars,
``pconnector/client/client.go:45``) -- no inherited ``PATH``. A
``pip install``-then-shebang-script approach (relying on
``#!/usr/bin/env python3`` resolving via ``PATH``, or an activated venv)
cannot launch under Conduit for exactly this reason -- this was flagged in
the design doc's Risks & open questions as a packaging gap this repo's own
Lane D closes. This module is that fix: it builds a single-file artifact
whose embedded shebang is an **absolute** interpreter path resolved at
build time (never looked up via ``PATH`` at exec time), with every
third-party dependency the connector needs bundled directly into the
archive.

**Vendoring strategy: vendor from the current environment, not a fresh
``pip install``.** Rather than re-resolving dependencies via a fresh
install (which would fail outright for this SDK itself -- not yet
published to PyPI -- and adds a network dependency to every build), this
vendors packages directly from the *current Python environment's*
already-installed distributions, using ``importlib.metadata`` to enumerate
each distribution's own files and transitive requirements. This is the
same fundamental assumption PEX/``shiv`` builds ultimately rely on (a
resolved environment) minus a redundant second dependency-resolution step.
Practical consequence: ``build`` must be run from an environment where the
connector's dependencies are already installed (however you installed them
-- pip, uv, poetry) -- this is a documented precondition, not a silent
requirement.

**Why this isn't a plain ``zipapp`` (the extension-module problem, found
while testing this exact command):** ``zipimport``/``zipapp`` cannot load
compiled extension modules (``.so``/``.pyd``/``.dylib``) directly from
inside a zip archive. This SDK's own core dependencies are not all pure
Python -- ``grpcio`` and ``pydantic``'s ``pydantic-core`` both ship
compiled extensions -- so a naive zipapp containing them would fail at
import time. The fix, the same one ``shiv``/``pex`` use: the artifact is
still a single zip file with an executable shebang, but its ``__main__.py``
is a small, dependency-free **bootstrap** that extracts the real payload
(everything vendored, including compiled extensions) to a per-build cache
directory on disk on first run, then executes the connector's real entry
point from those extracted, real files -- never via zipimport for the
parts that can't support it. Subsequent launches reuse the cached
extraction (keyed by a content hash of the archive), so the extraction
cost is paid once, not on every subprocess launch.
"""

from __future__ import annotations

import contextlib
import importlib.metadata
import shutil
import sys
import tempfile
import tomllib
import zipapp
from collections.abc import Iterator
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

_CONDUIT_SDK_DIST_NAME = "conduit-connector-sdk"
_SKIP_TOP_LEVEL_SUFFIXES = (".dist-info", ".data")
_SKIP_SOURCE_NAMES = frozenset(
    {"pyproject.toml", "uv.lock", "poetry.lock", "README.md", "__pycache__", ".git"}
)
_PAYLOAD_DIR_NAME = "_payload"

# The bootstrap that becomes the archive's own top-level `__main__.py`.
# Deliberately stdlib-only (no `conduit` import) -- it runs *before* the
# real payload (including this SDK itself) has been extracted anywhere
# `sys.path` can see it. See module docstring for why this exists at all.
_BOOTSTRAP_SOURCE = '''\
"""Auto-generated by `conduit-connector-sdk build` -- do not edit.

Extracts this archive's vendored payload (which may contain compiled
extension modules `zipimport` cannot load in place -- grpcio and
pydantic-core, both core dependencies of the connector SDK, are exactly
this case) to a per-build cache directory on first run, then executes the
real connector entry point from there. Later launches of the same archive
(same content hash) reuse the cached extraction.
"""

from __future__ import annotations

import hashlib
import os
import runpy
import sys
import zipfile
from pathlib import Path

_PAYLOAD_PREFIX = "_payload/"


def _cache_root() -> Path:
    override = os.environ.get("CONDUIT_CONNECTOR_BUILD_CACHE_DIR")
    if override:
        return Path(override)
    return Path.home() / ".cache" / "conduit-connector-sdk" / "builds"


def _extract_payload(archive_path: Path) -> Path:
    # Known limitation, not addressed here: two processes launching this
    # same archive for the very first time concurrently can race on this
    # check-then-extract sequence. Since both would extract byte-identical
    # content from the same source archive to the same destination paths,
    # this is not a correctness risk in practice (no partial/torn file can
    # result from two writers writing identical bytes), but it is not
    # formally locked -- a follow-up could add a lockfile if this ever
    # matters for a real deployment's concurrent-launch pattern.
    digest = hashlib.sha256(archive_path.read_bytes()).hexdigest()[:16]
    target = _cache_root() / digest
    marker = target / ".extracted-ok"
    if not marker.exists():
        target.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(archive_path) as archive:
            for name in archive.namelist():
                if name.startswith(_PAYLOAD_PREFIX) and not name.endswith("/"):
                    archive.extract(name, target)
        marker.touch()
    return target / "_payload"


def _main() -> None:
    archive_path = Path(sys.argv[0]).resolve()
    payload_dir = _extract_payload(archive_path)
    sys.path.insert(0, str(payload_dir))
    runpy.run_path(str(payload_dir / "__main__.py"), run_name="__main__")


_main()
'''


class BuildError(Exception):
    """Raised when :func:`build_connector_artifact` cannot produce an artifact.

    Every raise site here is meant to be actionable (``CLAUDE.md``'s
    "errors are API" standard): each message says what's missing and, where
    there's a clear next step, what to do about it.
    """


def build_connector_artifact(
    project_dir: Path,
    output_path: Path,
    *,
    entry_point: str = "main.py",
    interpreter: str | None = None,
) -> Path:
    """Build a self-contained, directly-executable artifact for a connector project.

    Args:
        project_dir: path to the connector project (containing at least
            ``entry_point`` and, if it declares third-party dependencies
            beyond this SDK, a ``pyproject.toml`` with a
            ``[project] dependencies`` list -- see module docstring's
            vendoring-strategy note for what "declares" means in practice).
        output_path: where to write the artifact. Parent directories are
            created if needed.
        entry_point: the connector's entry script within ``project_dir``,
            default ``main.py`` -- becomes the extracted payload's own
            ``__main__.py`` (see module docstring's bootstrap note),
            preserving the ``if __name__ == "__main__":`` guard authors
            already write (design doc §2.7's worked example) unmodified.
        interpreter: absolute path to embed in the artifact's shebang.
            Defaults to ``sys.executable`` -- already guaranteed absolute
            by Python itself, satisfying the "no ``PATH`` lookup at exec
            time" requirement with no extra effort in the common case of
            building with the same interpreter you'll deploy with.

    Returns:
        ``output_path``, for chaining.

    Raises:
        BuildError: if ``entry_point`` doesn't exist under ``project_dir``,
            or if a declared dependency isn't installed in the current
            environment.
    """
    project_dir = Path(project_dir).resolve()
    output_path = Path(output_path).resolve()
    entry_script = project_dir / entry_point
    if not entry_script.is_file():
        raise BuildError(f"entry point {entry_script} does not exist")

    dependency_names = _project_dependency_names(project_dir / "pyproject.toml")
    sdk_name = canonicalize_name(_CONDUIT_SDK_DIST_NAME)
    if sdk_name in dependency_names:
        # conduit-connector-sdk itself is vendored directly from this
        # running interpreter's own installed copy (see
        # _vendor_conduit_sdk) -- an editable dev install (this repo's own
        # setup) has no real files `importlib.metadata` can enumerate for
        # it (its `RECORD` only lists a `.pth` redirect), so *it* is
        # special-cased. Its own runtime dependencies (grpcio, protobuf,
        # pydantic, grpcio-health-checking, ...) are NOT special-cased,
        # though -- those need vendoring like any other dependency, or the
        # resulting artifact only happens to work when its embedded
        # interpreter shebang points at an environment that already has
        # them installed (verified: building without this line produces an
        # artifact that "works" only by accident, shebang'd to the dev
        # venv it was built in -- not actually self-contained).
        dependency_names.discard(sdk_name)
        dependency_names |= _direct_requirement_names(sdk_name)

    with _temporary_build_dir() as staging_dir:
        payload_dir = staging_dir / _PAYLOAD_DIR_NAME
        payload_dir.mkdir()

        _vendor_conduit_sdk(payload_dir)
        for dist_name in _resolve_transitive_distributions(dependency_names):
            _vendor_distribution(dist_name, payload_dir)
        _copy_connector_source(project_dir, payload_dir, entry_script)

        (staging_dir / "__main__.py").write_text(_BOOTSTRAP_SOURCE)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        zipapp.create_archive(
            staging_dir,
            target=output_path,
            interpreter=interpreter or sys.executable,
        )

    return output_path


@contextlib.contextmanager
def _temporary_build_dir() -> Iterator[Path]:
    with tempfile.TemporaryDirectory(prefix="conduit-connector-sdk-build-") as tmp:
        yield Path(tmp)


def _project_dependency_names(pyproject_path: Path) -> set[str]:
    """Read ``[project] dependencies`` from a connector's ``pyproject.toml``.

    Returns an empty set if there's no ``pyproject.toml`` at all -- a
    connector with no declared third-party dependencies (beyond this SDK)
    is valid; :func:`_vendor_conduit_sdk` still runs regardless.
    """
    if not pyproject_path.is_file():
        return set()
    data = tomllib.loads(pyproject_path.read_text())
    raw_dependencies = data.get("project", {}).get("dependencies", [])
    return {canonicalize_name(Requirement(spec).name) for spec in raw_dependencies}


def _resolve_transitive_distributions(root_names: set[str]) -> list[str]:
    """Breadth-first resolve every distribution a set of root deps needs.

    Uses each already-installed distribution's own recorded
    ``Requires-Dist`` metadata (``importlib.metadata.Distribution.requires``),
    skipping extras-conditional requirements (evaluated with no extras
    active) and anything already resolved. This is metadata-only: it
    trusts the *installed* distribution's own recorded dependency graph,
    not a fresh dependency resolution.

    Args:
        root_names: canonicalized top-level dependency names.

    Returns:
        Every distribution name (canonicalized), root and transitive, that
        needs vendoring.

    Raises:
        BuildError: if a required distribution isn't installed in the
            current environment.
    """
    resolved: list[str] = []
    seen: set[str] = set()
    queue = list(root_names)
    while queue:
        name = queue.pop()
        if name in seen:
            continue
        seen.add(name)
        resolved.append(name)
        for dep_name in _direct_requirement_names(name):
            if dep_name not in seen:
                queue.append(dep_name)
    return resolved


def _direct_requirement_names(dist_name: str) -> set[str]:
    """Return the canonicalized names of ``dist_name``'s own non-extra requirements.

    Skips extras-conditional requirements (evaluated with no extras
    active -- nothing this command builds requests an extra).

    Args:
        dist_name: canonicalized distribution name.

    Returns:
        Canonicalized names of every unconditional runtime dependency.

    Raises:
        BuildError: if ``dist_name`` isn't installed in the current
            environment.
    """
    try:
        dist = importlib.metadata.distribution(dist_name)
    except importlib.metadata.PackageNotFoundError as exc:
        raise BuildError(
            f"dependency {dist_name!r} is not installed in the current "
            "environment -- `build` vendors from already-installed "
            "distributions (see conduit._build's module docstring); "
            f"install it here first (e.g. `pip install {dist_name}`)"
        ) from exc
    names: set[str] = set()
    for requirement_str in dist.requires or ():
        requirement = Requirement(requirement_str)
        if requirement.marker is not None and not requirement.marker.evaluate({"extra": ""}):
            continue  # an optional extra this build doesn't request
        names.add(canonicalize_name(requirement.name))
    return names


def _vendor_distribution(dist_name: str, payload_dir: Path) -> None:
    """Copy one already-installed distribution's real files into ``payload_dir``.

    Compiled extension modules are copied like any other file here --
    unlike a plain zipapp, this artifact's bootstrap extracts the payload
    to real files on disk before ever importing anything from it (see
    module docstring), so a ``.so``/``.pyd``/``.dylib`` works fine.

    Args:
        dist_name: canonicalized distribution name.
        payload_dir: destination root (the extracted payload's future root).

    Raises:
        BuildError: if the distribution has no file manifest (see
            :func:`_resolve_transitive_distributions`'s docstring on
            editable installs).
    """
    dist = importlib.metadata.distribution(dist_name)
    if dist.files is None:
        raise BuildError(
            f"distribution {dist_name!r} has no file manifest (RECORD) -- "
            "cannot vendor it. Is it installed in editable/development "
            "mode? Only conduit-connector-sdk itself is special-cased for "
            "that (see _vendor_conduit_sdk); a real dependency needs a "
            "normal (non-editable) install in this environment to be "
            "vendored."
        )
    for file in dist.files:
        if str(file).startswith(".."):
            continue  # outside the distribution's own tree, e.g. a console-script shim
        if any(part.endswith(_SKIP_TOP_LEVEL_SUFFIXES) for part in file.parts):
            continue  # *.dist-info / *.data housekeeping, not importable code
        source = file.locate()
        if not Path(source).is_file():
            continue
        destination = payload_dir / file
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def _vendor_conduit_sdk(payload_dir: Path) -> None:
    """Copy this SDK's own package directory into ``payload_dir`` directly.

    Bypasses ``importlib.metadata`` entirely: works identically whether
    this SDK is installed normally or (as in this repo's own dev setup)
    in editable mode, since it just asks Python's own import system where
    ``conduit`` actually lives, rather than reading install metadata.
    """
    import conduit  # local import: this is the package this module lives in

    conduit_dir = Path(conduit.__file__).resolve().parent
    shutil.copytree(conduit_dir, payload_dir / "conduit", dirs_exist_ok=True)


def _copy_connector_source(project_dir: Path, payload_dir: Path, entry_script: Path) -> None:
    """Copy a connector project's own source into ``payload_dir``.

    Skips packaging/VCS housekeeping (``pyproject.toml``, lockfiles,
    ``README.md``, ``__pycache__``, ``.git``) -- everything else in
    ``project_dir`` is assumed to be the connector's own source and is
    copied verbatim, so a connector split across multiple modules (not
    just a single ``main.py``) still works.
    """
    for item in project_dir.iterdir():
        if item.name in _SKIP_SOURCE_NAMES or item.name.startswith("."):
            continue
        destination = payload_dir / item.name
        if item.is_dir():
            shutil.copytree(item, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(item, destination)

    # The bootstrap's `runpy.run_path` looks for `__main__.py` at the
    # extracted payload's root (see _BOOTSTRAP_SOURCE) -- copy (not move,
    # not a symlink: the zip needs a real file) the connector's own entry
    # script there.
    shutil.copy2(entry_script, payload_dir / "__main__.py")
