# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from connector.v2 import destination_pb2 as connector_dot_v2_dot_destination__pb2


class DestinationPluginStub(object):
    """DestinationPlugin is responsible for writing records to 3rd party resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/connector.v2.DestinationPlugin/Configure',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Configure.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Configure.Response.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/connector.v2.DestinationPlugin/Open',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Open.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Open.Response.FromString,
                _registered_method=True)
        self.Run = channel.stream_stream(
                '/connector.v2.DestinationPlugin/Run',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Run.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Run.Response.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/connector.v2.DestinationPlugin/Stop',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Stop.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Stop.Response.FromString,
                _registered_method=True)
        self.Teardown = channel.unary_unary(
                '/connector.v2.DestinationPlugin/Teardown',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Teardown.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Teardown.Response.FromString,
                _registered_method=True)
        self.LifecycleOnCreated = channel.unary_unary(
                '/connector.v2.DestinationPlugin/LifecycleOnCreated',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Response.FromString,
                _registered_method=True)
        self.LifecycleOnUpdated = channel.unary_unary(
                '/connector.v2.DestinationPlugin/LifecycleOnUpdated',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Response.FromString,
                _registered_method=True)
        self.LifecycleOnDeleted = channel.unary_unary(
                '/connector.v2.DestinationPlugin/LifecycleOnDeleted',
                request_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Response.FromString,
                _registered_method=True)


class DestinationPluginServicer(object):
    """DestinationPlugin is responsible for writing records to 3rd party resources.
    """

    def Configure(self, request, context):
        """Configure is the first function to be called in a plugin. It provides the
        plugin with the configuration that needs to be validated and stored. In
        case the configuration is not valid it should return an error status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Open is called after Configure to signal the plugin it can prepare to
        start writing records. If needed, the plugin should open connections in
        this function.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request_iterator, context):
        """Run will open a bidirectional stream between Conduit and the plugin.
        Conduit will be streaming records to the plugin that should be written
        to the 3rd party resource. The plugin is responsible for sending
        acknowledgments back to Conduit once a record has been processed. The
        acknowledgment should contain an error in case a record could not be
        successfully processed. The stream should still stay open in case Conduit
        is able to recover from the error and the pipeline keeps running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop signals to the plugin that the record with the specified position is
        the last one and no more records will be written to the stream after it.
        Once the plugin receives the last record it should flush any records that
        might be cached and not yet written to the 3rd party resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Teardown signals to the plugin that there will be no more calls to any
        other function. After Teardown returns, the plugin should be ready for a
        graceful shutdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnCreated(self, request, context):
        """-- Lifecycle events -------------------------------------------------------

        LifecycleOnCreated is called after Configure and before Open when the
        connector is run for the first time. This call will be skipped if a
        connector was already started before. This method can be used to do some
        initialization that needs to happen only once in the lifetime of a
        connector (e.g. create a bucket). Anything that the connector creates in
        this method is considered to be owned by this connector and should be
        cleaned up in LifecycleOnDeleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnUpdated(self, request, context):
        """LifecycleOnUpdated is called after Configure and before Open when the
        connector configuration has changed since the last run. This call will be
        skipped if the connector configuration did not change. It can be used to
        update anything that was initialized in LifecycleOnCreated, in case the
        configuration change affects it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnDeleted(self, request, context):
        """LifecycleOnDeleted is called when the connector was deleted. It will be the
        only method that is called in that case. This method can be used to clean
        up anything that was initialized in LifecycleOnCreated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DestinationPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Configure.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Configure.Response.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Open.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Open.Response.SerializeToString,
            ),
            'Run': grpc.stream_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Run.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Run.Response.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Stop.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Stop.Response.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Teardown.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Teardown.Response.SerializeToString,
            ),
            'LifecycleOnCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnCreated,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Response.SerializeToString,
            ),
            'LifecycleOnUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnUpdated,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Response.SerializeToString,
            ),
            'LifecycleOnDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnDeleted,
                    request_deserializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Request.FromString,
                    response_serializer=connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connector.v2.DestinationPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('connector.v2.DestinationPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DestinationPlugin(object):
    """DestinationPlugin is responsible for writing records to 3rd party resources.
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/Configure',
            connector_dot_v2_dot_destination__pb2.Destination.Configure.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Configure.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/Open',
            connector_dot_v2_dot_destination__pb2.Destination.Open.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Open.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/connector.v2.DestinationPlugin/Run',
            connector_dot_v2_dot_destination__pb2.Destination.Run.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Run.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/Stop',
            connector_dot_v2_dot_destination__pb2.Destination.Stop.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Stop.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/Teardown',
            connector_dot_v2_dot_destination__pb2.Destination.Teardown.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Teardown.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/LifecycleOnCreated',
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnCreated.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/LifecycleOnUpdated',
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnUpdated.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.DestinationPlugin/LifecycleOnDeleted',
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Request.SerializeToString,
            connector_dot_v2_dot_destination__pb2.Destination.Lifecycle.OnDeleted.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
