# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from connector.v2 import source_pb2 as connector_dot_v2_dot_source__pb2


class SourcePluginStub(object):
    """SourcePlugin is responsible for fetching records from 3rd party resources and
    sending them to Conduit.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/connector.v2.SourcePlugin/Configure',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Configure.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Configure.Response.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/connector.v2.SourcePlugin/Open',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Open.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Open.Response.FromString,
                _registered_method=True)
        self.Run = channel.stream_stream(
                '/connector.v2.SourcePlugin/Run',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Run.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Run.Response.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/connector.v2.SourcePlugin/Stop',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Stop.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Stop.Response.FromString,
                _registered_method=True)
        self.Teardown = channel.unary_unary(
                '/connector.v2.SourcePlugin/Teardown',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Teardown.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Teardown.Response.FromString,
                _registered_method=True)
        self.LifecycleOnCreated = channel.unary_unary(
                '/connector.v2.SourcePlugin/LifecycleOnCreated',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Response.FromString,
                _registered_method=True)
        self.LifecycleOnUpdated = channel.unary_unary(
                '/connector.v2.SourcePlugin/LifecycleOnUpdated',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Response.FromString,
                _registered_method=True)
        self.LifecycleOnDeleted = channel.unary_unary(
                '/connector.v2.SourcePlugin/LifecycleOnDeleted',
                request_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Response.FromString,
                _registered_method=True)


class SourcePluginServicer(object):
    """SourcePlugin is responsible for fetching records from 3rd party resources and
    sending them to Conduit.
    """

    def Configure(self, request, context):
        """Configure is the first function to be called in a plugin. It provides the
        plugin with the configuration that needs to be validated and stored. In
        case the configuration is not valid it should return an error status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Open is called after Configure to signal the plugin it can prepare to
        start producing records. If needed, the plugin should open connections in
        this function. The position parameter will contain the position of the
        last record that was successfully processed. The Source should therefore
        start producing records after this position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request_iterator, context):
        """Run will open a bidirectional stream between Conduit and the plugin.
        The plugin is responsible for fetching records from 3rd party resources
        and sending them as responses to Conduit. Conduit will process the
        records asynchronously and send acknowledgments back to the plugin to
        signal that a record at a certain position was processed. Acknowledgments
        will be sent back to the connector in the same order as the records
        produced by the connector. If a record could not be processed by Conduit,
        the stream will be closed without an acknowledgment being sent back to the
        connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop signals to the plugin to stop retrieving new records and flush any
        records that might be cached into the stream. It should block until it can
        determine the last record that will be sent to the stream and return the
        position of the last record. Conduit will keep the stream open until it
        receives the last record and sends back any outstanding acknowledgments.
        If Conduit did not send an acknowledgment for a record after the stream is
        closed, it should be interpreted as a negative acknowledgment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Teardown signals to the plugin that there will be no more calls to any
        other function. After Teardown returns, the plugin should be ready for a
        graceful shutdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnCreated(self, request, context):
        """-- Lifecycle events -------------------------------------------------------

        LifecycleOnCreated is called after Configure and before Open when the
        connector is run for the first time. This call will be skipped if a
        connector was already started before. This method can be used to do some
        initialization that needs to happen only once in the lifetime of a
        connector (e.g. create a replication slot). Anything that the connector
        creates in this method is considered to be owned by this connector and
        should be cleaned up in LifecycleOnDeleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnUpdated(self, request, context):
        """LifecycleOnUpdated is called after Configure and before Open when the
        connector configuration has changed since the last run. This call will be
        skipped if the connector configuration did not change. It can be used to
        update anything that was initialized in LifecycleOnCreated, in case the
        configuration change affects it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LifecycleOnDeleted(self, request, context):
        """LifecycleOnDeleted is called when the connector was deleted. It will be the
        only method that is called in that case. This method can be used to clean
        up anything that was initialized in LifecycleOnCreated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourcePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Configure.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Configure.Response.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Open.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Open.Response.SerializeToString,
            ),
            'Run': grpc.stream_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Run.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Run.Response.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Stop.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Stop.Response.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Teardown.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Teardown.Response.SerializeToString,
            ),
            'LifecycleOnCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnCreated,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Response.SerializeToString,
            ),
            'LifecycleOnUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnUpdated,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Response.SerializeToString,
            ),
            'LifecycleOnDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.LifecycleOnDeleted,
                    request_deserializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Request.FromString,
                    response_serializer=connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connector.v2.SourcePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('connector.v2.SourcePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SourcePlugin(object):
    """SourcePlugin is responsible for fetching records from 3rd party resources and
    sending them to Conduit.
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/Configure',
            connector_dot_v2_dot_source__pb2.Source.Configure.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Configure.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/Open',
            connector_dot_v2_dot_source__pb2.Source.Open.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Open.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/connector.v2.SourcePlugin/Run',
            connector_dot_v2_dot_source__pb2.Source.Run.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Run.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/Stop',
            connector_dot_v2_dot_source__pb2.Source.Stop.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Stop.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/Teardown',
            connector_dot_v2_dot_source__pb2.Source.Teardown.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Teardown.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/LifecycleOnCreated',
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnCreated.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/LifecycleOnUpdated',
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnUpdated.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LifecycleOnDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SourcePlugin/LifecycleOnDeleted',
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Request.SerializeToString,
            connector_dot_v2_dot_source__pb2.Source.Lifecycle.OnDeleted.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
