# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connector/v2/specifier.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'connector/v2/specifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from config.v1 import parameter_pb2 as config_dot_v1_dot_parameter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63onnector/v2/specifier.proto\x12\x0c\x63onnector.v2\x1a google/protobuf/descriptor.proto\x1a\x19\x63onfig/v1/parameter.proto\"\xfb\x03\n\rSpecification\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07summary\x18\x02 \x01(\tR\x07summary\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07version\x18\x04 \x01(\tR\x07version\x12\x16\n\x06\x61uthor\x18\x05 \x01(\tR\x06\x61uthor\x12\x61\n\x12\x64\x65stination_params\x18\x06 \x03(\x0b\x32\x32.connector.v2.Specification.DestinationParamsEntryR\x11\x64\x65stinationParams\x12R\n\rsource_params\x18\x07 \x03(\x0b\x32-.connector.v2.Specification.SourceParamsEntryR\x0csourceParams\x1aZ\n\x16\x44\x65stinationParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x14.config.v1.ParameterR\x05value:\x02\x38\x01\x1aU\n\x11SourceParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x14.config.v1.ParameterR\x05value:\x02\x38\x01\"p\n\tSpecifier\x1a\x63\n\x07Specify\x1a\t\n\x07Request\x1aM\n\x08Response\x12\x41\n\rspecification\x18\x01 \x01(\x0b\x32\x1b.connector.v2.SpecificationR\rspecification2o\n\x0fSpecifierPlugin\x12\\\n\x07Specify\x12\'.connector.v2.Specifier.Specify.Request\x1a(.connector.v2.Specifier.Specify.ResponseBDZBgithub.com/conduitio/conduit-connector-protocol/proto/connector/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connector.v2.specifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/conduitio/conduit-connector-protocol/proto/connector/v2'
  _globals['_SPECIFICATION_DESTINATIONPARAMSENTRY']._loaded_options = None
  _globals['_SPECIFICATION_DESTINATIONPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SPECIFICATION_SOURCEPARAMSENTRY']._loaded_options = None
  _globals['_SPECIFICATION_SOURCEPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SPECIFICATION']._serialized_start=108
  _globals['_SPECIFICATION']._serialized_end=615
  _globals['_SPECIFICATION_DESTINATIONPARAMSENTRY']._serialized_start=438
  _globals['_SPECIFICATION_DESTINATIONPARAMSENTRY']._serialized_end=528
  _globals['_SPECIFICATION_SOURCEPARAMSENTRY']._serialized_start=530
  _globals['_SPECIFICATION_SOURCEPARAMSENTRY']._serialized_end=615
  _globals['_SPECIFIER']._serialized_start=617
  _globals['_SPECIFIER']._serialized_end=729
  _globals['_SPECIFIER_SPECIFY']._serialized_start=630
  _globals['_SPECIFIER_SPECIFY']._serialized_end=729
  _globals['_SPECIFIER_SPECIFY_REQUEST']._serialized_start=641
  _globals['_SPECIFIER_SPECIFY_REQUEST']._serialized_end=650
  _globals['_SPECIFIER_SPECIFY_RESPONSE']._serialized_start=652
  _globals['_SPECIFIER_SPECIFY_RESPONSE']._serialized_end=729
  _globals['_SPECIFIERPLUGIN']._serialized_start=731
  _globals['_SPECIFIERPLUGIN']._serialized_end=842
# @@protoc_insertion_point(module_scope)
