# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from connector.v2 import specifier_pb2 as connector_dot_v2_dot_specifier__pb2


class SpecifierPluginStub(object):
    """SpecifierPlugin is responsible for returning the plugin specification.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Specify = channel.unary_unary(
                '/connector.v2.SpecifierPlugin/Specify',
                request_serializer=connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Request.SerializeToString,
                response_deserializer=connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Response.FromString,
                _registered_method=True)


class SpecifierPluginServicer(object):
    """SpecifierPlugin is responsible for returning the plugin specification.
    """

    def Specify(self, request, context):
        """Specify should return the plugin specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpecifierPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Specify': grpc.unary_unary_rpc_method_handler(
                    servicer.Specify,
                    request_deserializer=connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Request.FromString,
                    response_serializer=connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connector.v2.SpecifierPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('connector.v2.SpecifierPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpecifierPlugin(object):
    """SpecifierPlugin is responsible for returning the plugin specification.
    """

    @staticmethod
    def Specify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connector.v2.SpecifierPlugin/Specify',
            connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Request.SerializeToString,
            connector_dot_v2_dot_specifier__pb2.Specifier.Specify.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
